### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by ChellappaSait** [SpectoLabs/hoverpy#6]
(.testenv) C:\Users\chell\hoverpy\examples\modify>python modify.py
Traceback (most recent call last):
  File "modify.py", line 20, in <module>
    if "time" in r.json().keys():
  File "C:\Users\chell\hoverpy\.testenv\lib\site-packages\requests\models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\python27\Lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\python27\Lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python27\Lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")

**Comment by shyal** [comment]
Hi Chellappa,

You should be running this from `C:\Users\chell\hoverpy`. With `python examples\modify\modify.py`.
